import os
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection


class DatabaseConnection:
    def __init__(self, connection: Connection):
        self._connection = connection
        self._transaction = connection.begin()

    def execute(self, statement, parameters=()):
        if isinstance(parameters, tuple):
            names = [f"param_{index}" for index in range(len(parameters))]
            statement = statement.replace("?", ":" + ", :".join(names))
            parameters = dict(zip(names, parameters))
        return self._connection.execute(text(statement), parameters)

    def commit(self):
        self._transaction.commit()
        self._transaction = self._connection.begin()

    def close(self):
        if self._transaction.is_active:
            self._transaction.commit()
        self._connection.close()


def get_db() -> DatabaseConnection:
    return DatabaseConnection(_get_engine().connect())


def _database_url() -> str | None:
    value = os.getenv("DATABASE_URL") or None
    if value and value.startswith("postgres://"):
        return value.replace("postgres://", "postgresql+psycopg://", 1)
    if value and value.startswith("postgresql://"):
        return value.replace("postgresql://", "postgresql+psycopg://", 1)
    return value


def _engine():
    url = _database_url()
    if url:
        return create_engine(url, pool_pre_ping=True, pool_recycle=300)
    db_path = Path(os.getenv("DB_PATH", "finance.db"))
    return create_engine(
        f"sqlite:///{db_path.resolve().as_posix()}",
        connect_args={"check_same_thread": False},
    )


_ENGINE = None


def _get_engine():
    global _ENGINE
    if _ENGINE is None:
        _ENGINE = _engine()
    return _ENGINE


def using_postgres() -> bool:
    return _database_url() is not None


@contextmanager
def db_connection() -> Iterator[Connection]:
    with _get_engine().begin() as conn:
        yield conn


def init_db() -> None:
    engine = _get_engine()
    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS accounts (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name TEXT NOT NULL,
                balance DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                type TEXT NOT NULL DEFAULT 'checking'
            )
        """ if using_postgres() else """
            CREATE TABLE IF NOT EXISTS accounts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                balance REAL NOT NULL DEFAULT 0.0,
                type TEXT NOT NULL DEFAULT 'checking'
            )
        """))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS transactions (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                type TEXT NOT NULL CHECK(type IN ('income','expense')),
                amount DOUBLE PRECISION NOT NULL,
                description TEXT NOT NULL,
                category TEXT NOT NULL,
                date TEXT NOT NULL,
                created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                account_id INTEGER REFERENCES accounts(id)
            )
        """ if using_postgres() else """
            CREATE TABLE IF NOT EXISTS transactions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                type TEXT NOT NULL CHECK(type IN ('income','expense')),
                amount REAL NOT NULL,
                description TEXT NOT NULL,
                category TEXT NOT NULL,
                date TEXT NOT NULL,
                created TEXT DEFAULT (datetime('now')),
                account_id INTEGER REFERENCES accounts(id)
            )
        """))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS budgets (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                category TEXT UNIQUE NOT NULL,
                limit_amt DOUBLE PRECISION NOT NULL
            )
        """ if using_postgres() else """
            CREATE TABLE IF NOT EXISTS budgets (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                category TEXT UNIQUE NOT NULL,
                limit_amt REAL NOT NULL
            )
        """))
        if using_postgres():
            conn.execute(text("""
                ALTER TABLE transactions ADD COLUMN IF NOT EXISTS account_id INTEGER
            """))
            conn.execute(text("""
                ALTER TABLE accounts ADD COLUMN IF NOT EXISTS type TEXT NOT NULL DEFAULT 'checking'
            """))
        else:
            columns = {row[1] for row in conn.exec_driver_sql("PRAGMA table_info(transactions)")}
            if "account_id" not in columns:
                conn.execute(text("ALTER TABLE transactions ADD COLUMN account_id INTEGER"))
            account_columns = {row[1] for row in conn.exec_driver_sql("PRAGMA table_info(accounts)")}
            if "type" not in account_columns:
                conn.execute(text("ALTER TABLE accounts ADD COLUMN type TEXT NOT NULL DEFAULT 'checking'"))


def reset_engine_for_tests() -> None:
    global _ENGINE
    if _ENGINE is not None:
        _ENGINE.dispose()
    _ENGINE = None
